USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/asus/anthias/BoardConfigVendor.mk

TARGET_ARCH := arm
TARGET_BOARD_PLATFORM := bcm_java
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT:= cortex-a7
ARCH_ARM_HAVE_TLS_REGISTER := true


TARGET_GLOBAL_CFLAGS += -mfpu=neon -mfloat-abi=softfp
TARGET_GLOBAL_CPPFLAGS += -mfpu=neon -mfloat-abi=softfp

COMMON_GLOBAL_CFLAGS += -DREFRESH_RATE=60 -DBINDER_COMPAT

TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true
TARGET_BOOTLOADER_BOARD_NAME := anthias

BOARD_KERNEL_CMDLINE := 
BOARD_KERNEL_BASE := 0x0008000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_BOOTIMAGE_PARTITION_SIZE := 23068672
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 23068672
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 536870912
BOARD_USERDATAIMAGE_PARTITION_SIZE := 2873867264
BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_VOLD_EMMC_SHARES_DEV_MAJOR := true

# Custom recovery
TARGET_PREBUILT_KERNEL := device/asus/anthias/kernel
TARGET_PREBUILT_RECOVERY_KERNEL := device/asus/anthias/kernel
TARGET_RECOVERY_PIXEL_FORMAT := "RGB_565"
BOARD_HAS_NO_SELECT_BUTTON := true
BOARD_HAS_LARGE_FILESYSTEM := true
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_RECOVERY_FSTAB := device/asus/anthias/config/twrp.fstab


DEVICE_RESOLUTION := 320x320
RECOVERY_GRAPHICS_USE_LINELENGTH := true
TW_INTERNAL_STORAGE_PATH := "/data/media"
TW_INTERNAL_STORAGE_MOUNT_POINT := "data"
TW_NO_USB_STORAGE := true
TW_MAX_BRIGHTNESS := 255
TW_EXCLUDE_SUPERSU := true
